# Generated by Django 3.2.7 on 2021-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('organizadore', models.TextField()),
                ('inicio', models.IntegerField()),
                ('fim', models.IntegerField()),
            ],
        ),
    ]
