# Generated by Django 3.2.7 on 2021-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='organizadores',
        ),
        migrations.AddField(
            model_name='evento',
            name='organizadores',
            field=models.CharField(default=1, max_length=200, verbose_name='Organizadores'),
            preserve_default=False,
        ),
    ]
