# Generated by Django 3.2.7 on 2021-09-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='organizadore',
            new_name='organizadores',
        ),
    ]
