# Generated by Django 3.2.7 on 2021-09-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='organizadores',
        ),
    ]
