# Generated by Django 3.2.7 on 2021-09-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_organizadore_evento_organizadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
