# Generated by Django 3.2.7 on 2021-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadores', '0001_initial'),
        ('core', '0002_remove_evento_organizadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='organizadores',
            field=models.ManyToManyField(to='organizadores.Organizadore'),
        ),
    ]
