# Generated by Django 3.2.7 on 2021-09-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210907_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='url',
        ),
    ]
