# Generated by Django 3.2.7 on 2021-09-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='organizadores',
        ),
    ]
