# Generated by Django 3.2 on 2021-09-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=45)),
                ('inicio', models.CharField(blank=True, max_length=10)),
                ('fim', models.CharField(blank=True, max_length=10)),
                ('sucesso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizadores', to='socializei.evento')),
            ],
            options={
                'verbose_name': 'Organzador',
                'verbose_name_plural': 'Organizadores',
                'unique_together': {('nome', 'sobrenome', 'evento')},
            },
        ),
    ]
