# Generated by Django 3.2 on 2021-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socializei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='sucesso',
            field=models.CharField(blank=True, default='true', max_length=5),
        ),
    ]
