# Generated by Django 3.2 on 2021-09-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socializei', '0002_alter_evento_sucesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='sucesso',
        ),
    ]
