# Generated by Django 3.2 on 2021-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socializei', '0003_remove_evento_sucesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=45),
        ),
    ]
