# Generated by Django 3.2 on 2021-09-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socializei', '0004_alter_evento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='sucesso',
            field=models.CharField(blank=True, default='true', max_length=5),
        ),
    ]
